services:


# DATABASE CONTAINER
  db:
    image: mysql:8.0.29-oracle
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d


# ACTIVEMQ CONTAINER
  activemq:
    build:
      ../.
    restart: unless-stopped
    ports:
      - 8161:8161
      - 61616:61616



# BANK CONTAINER
  bank:
    depends_on:
      - db
    build: .
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://db:3306/bankdb?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.activemq.broker-url" : "tcp://activemq:61616" }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true


  # LOGGER CONTAINER
  logger:
    depends_on:
      - db
    build: ../statlogger/.
    restart: on-failure
    ports:
      - "8081:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://db:3306/loggerdb?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.activemq.broker-url" : "tcp://activemq:61616" }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true



volumes:
  db: