server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankdb
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  activemq:
    broker-url: tcp://localhost:61616


#spring:
#  datasource:
#    continue-on-error: true
#    initialization-mode: always
#    password: VerySecretPassword
#  cloud:
#    gcp:
#      sql:
#        database-name: bankdb
#        instance-connection-name: banking-system-349517:europe-west3:bankdb
#

# msg:
#  title: Banking System 2000