spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bankdb
    username: root
    password: MyN3wP4ssw0rd
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect